[tool.ruff]
line-length = 120
select = ["E", "F", "W"]
ignore = ["E501"]  # Ignore long line errors
exclude = ["migrations", "__pycache__", "tests/old"]
extend-ignore = ["F401"]  # Ignore unused imports

[tool.ruff.lint]
select = ["E501", "I"]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 120
