# Generated by Django 5.1.1 on 2024-09-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('contract_address', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('circulating_supply', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('total_supply', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('max_supply', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('network', models.CharField(max_length=255, null=True)),
                ('ath', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('atl', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'asset')},
            },
        ),
    ]
