# Generated by Django 5.1.1 on 2024-10-05 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='price',
            new_name='current_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='network',
        ),
        migrations.AddField(
            model_name='asset',
            name='ath_change_percentage',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ath_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='atl_change_percentage',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='atl_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='high_24h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='low_24h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_percentage_24h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='walletasset',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.wallet'),
        ),
    ]
