# Generated by Django 5.1.1 on 2024-09-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_delete_assets_wallet_name_wallet_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ath',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='atl',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='contract_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='max_supply',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='network',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='total_supply',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
