# Generated by Django 5.1.1 on 2024-09-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_asset_ath_alter_asset_atl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='amount',
        ),
    ]
